### ISSUE TITLE
Will this work if I use JavaScript instead of TypeScript?

### ISSUE THREAD

**Issue by badri119** [NativSibony/react-card-swiper#2]
Hi, 

I want to use this npm package and I love it. I am wondering if this will work with JS in react? 

Furthermore, I went through the usage example and converted my code to JS, but I get a lot of errors.  

Also, I am wondering if the usage example is correct?

Thanks!

**Comment by NativSibony** [comment]
Yes, thank you for your input, I had a small fix to make in th documentation and the demo, 
please install v1.1.25 latest version.

Here is a working example using react-vite with javascript only -

```jsx 
import { CardSwiper } from "react-card-swiper"
import ReactSvg from "../src/assets/react.svg"

const Content = () => (
  <h1>
    Lorem ipsum dolor sit amet.
  </h1>
)

function App() {
  const mockData = [{ id: '88552078', meta: { apk: 'some-apk-a.apk' }, src: ReactSvg, content: <Content /> }]
  
  return (
    <div style={{width: "100%", height: "100%", display: "flex", justifyContent:"center", alignItems:"center"}}>
      <div style={{width: "300px", height:"500px"}}>
        <CardSwiper data={mockData} emptyState={<div>Empty State</div>} />
      </div>
    </div>
  )
}

export default App
```
